openapi: 3.0.1
info:
  title: Complex
  version: 0.1.0
servers:
- url: "{server}:{port}/complex"
  variables:
    server:
      default: http://localhost
    port:
      default: "8080"
paths:
  /getIssuesFixingFrequency:
    get:
      operationId: getGetissuesfixingfrequency
      parameters:
      - name: ownername
        in: query
        required: true
        schema:
          type: string
      - name: reponame
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /getBugFixRatio:
    get:
      operationId: getGetbugfixratio
      parameters:
      - name: ownername
        in: query
        required: true
        schema:
          type: string
      - name: reponame
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /getMeanLeadFixTime:
    get:
      operationId: getGetmeanleadfixtime
      parameters:
      - name: ownername
        in: query
        required: true
        schema:
          type: string
      - name: reponame
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /getPullRequestFrequency:
    get:
      operationId: getGetpullrequestfrequency
      parameters:
      - name: ownername
        in: query
        required: true
        schema:
          type: string
      - name: reponame
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
components: {}
