openapi: 3.0.1
info:
  title: Primitive2
  version: 0.1.0
servers:
- url: "{server}:{port}/primitive2"
  variables:
    server:
      default: http://localhost
    port:
      default: "8080"
paths:
  /userDetails:
    get:
      operationId: getUserdetails
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
components: {}
