openapi: 3.0.1
info:
  title: User
  version: 0.1.0
servers: []
paths:
  /getAllRepos:
    get:
      operationId: getGetallrepos
      responses:
        "200":
          description: Ok
          content:
            ? "application/{\r\n        allowOrigins: [http://localhost:3000]\r\n\
              \    }+json"
            : schema:
                type: object
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /addRepo:
    post:
      operationId: postAddrepo
      requestBody:
        content:
          ? "application/{\r\n        allowOrigins: [http://localhost:3000]\r\n  \
            \  }+json"
          : schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        "200":
          description: Ok
          content:
            ? "application/{\r\n        allowOrigins: [http://localhost:3000]\r\n\
              \    }+json"
            : schema:
                type: object
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /changeUserGroup:
    put:
      operationId: putChangeusergroup
      parameters:
      - name: userId
        in: query
        required: true
        schema:
          type: string
      - name: groupName
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            ? "application/{\r\n        allowOrigins: [http://localhost:3000]\r\n\
              \    }+json"
            : schema:
                type: object
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /addUserToGroup:
    post:
      operationId: postAddusertogroup
      parameters:
      - name: userId
        in: query
        required: true
        schema:
          type: string
      requestBody:
        content:
          ? "text/{\r\n        allowOrigins: [http://localhost:3000]\r\n    }+plain"
          : schema: {}
      responses:
        "200":
          description: Ok
          content:
            ? "application/{\r\n        allowOrigins: [http://localhost:3000]\r\n\
              \    }+json"
            : schema:
                type: object
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /removeUserGroup:
    delete:
      operationId: deleteRemoveusergroup
      parameters:
      - name: userId
        in: query
        required: true
        schema:
          type: string
      requestBody:
        content:
          ? "text/{\r\n        allowOrigins: [http://localhost:3000]\r\n    }+plain"
          : schema: {}
      responses:
        "200":
          description: Ok
          content:
            ? "application/{\r\n        allowOrigins: [http://localhost:3000]\r\n\
              \    }+json"
            : schema:
                type: object
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    UserRequest:
      required:
      - repo
      - user
      type: object
      properties:
        user:
          type: string
        repo:
          type: string
